In [ ]:
x=[1,2,3,45,2,3,45,8]
b= set(x)
print(b)

maximum = max(x)
minimum = min(x)
print(maximum)
print(minimum)


{1, 2, 3, 8, 45}
45
1


In [ ]:
import numpy as np
df = np.arange(1,21)
print(df)
df=df[df>10]
print(df)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20]


In [ ]:
import numpy as np
arr = np.array([[1,2,3],
               [4,5,6]])

print(arr.reshape(3,2))
print(arr.flatten())

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
import pandas as pd

df=pd.read_csv("sample_data.csv")
print(df)

print(df.isnull().sum())

      Name  Gender       City Passed
0     Aman    Male      Delhi    Yes
1    Priya  Female     Mumbai    Yes
2    Rahul    Male  Bangalore     No
3   Anjali  Female     Mumbai    Yes
4     Ravi    Male      Delhi    Yes
5    Meera  Female     Chenai     No
6    Arjun    Male  Bangalore    Yes
7     Neha  Female      Delhi    Yes
8   Imaran    Male     Chenai     No
9    Sneha  Female     Mumbai    Yes
10     Raj     NaN     Chenai    Yes
11   Divya  Female      Delhi     No
12   Kabir    Male     Mumbai    Yes
13  Simran  Female  Bangalore    Yes
14   Karan    Male      Delhi     No
15   Pooja  Female     Mumbai    Yes
16  Rakesh    Male        Nan    Yes
17    Isha  Female      Delhi     No
18   Rohit    Male      Delhi    Yes
19   Deepa  Female  Bangalore    NaN
Name      0
Gender    1
City      0
Passed    1
dtype: int64


In [ ]:
import pandas as pd
df = pd.read_csv("sample_data.csv")

print(df.fillna(0))

      Name  Gender       City Passed
0     Aman    Male      Delhi    Yes
1    Priya  Female     Mumbai    Yes
2    Rahul    Male  Bangalore     No
3   Anjali  Female     Mumbai    Yes
4     Ravi    Male      Delhi    Yes
5    Meera  Female     Chenai     No
6    Arjun    Male  Bangalore    Yes
7     Neha  Female      Delhi    Yes
8   Imaran    Male     Chenai     No
9    Sneha  Female     Mumbai    Yes
10     Raj       0     Chenai    Yes
11   Divya  Female      Delhi     No
12   Kabir    Male     Mumbai    Yes
13  Simran  Female  Bangalore    Yes
14   Karan    Male      Delhi     No
15   Pooja  Female     Mumbai    Yes
16  Rakesh    Male        Nan    Yes
17    Isha  Female      Delhi     No
18   Rohit    Male      Delhi    Yes
19   Deepa  Female  Bangalore      0


In [ ]:
import pandas as pd
data = ({
    "Name":["sonu","monu","rohit","vikesh","nitesh"],
    "Salary":[20000,22000,18000,28000,30000]
})
df = pd.DataFrame(data)

print(df)
max_salary = df[df["Salary"]>20000]
print(max_salary)

     Name  Salary
0    sonu   20000
1    monu   22000
2   rohit   18000
3  vikesh   28000
4  nitesh   30000
     Name  Salary
1    monu   22000
3  vikesh   28000
4  nitesh   30000


In [ ]:
print(df)
print(df.loc[1,"Name"])
print(df.iloc[2,1])

     Name  Salary
0    sonu   20000
1    monu   22000
2   rohit   18000
3  vikesh   28000
4  nitesh   30000
monu
18000


In [ ]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

y_true=[1,0,1,1,0,1,0]

y_pred=[1,0,1,0,0,1,1]

print("Accuracy",accuracy_score(y_true,y_pred))
print("Precision",precision_score(y_true,y_pred))
print("Recall",recall_score(y_true,y_pred))
print("F1 score",f1_score(y_true,y_pred))

Accuracy 0.7142857142857143
Precision 0.75
Recall 0.75
F1 score 0.75


In [ ]:
from sklearn.metrics import confusion_matrix

y_true = [1,0,1,1,0,1,0,0,1,0]
y_pred = [1,0,1,0,0,1,1,0,1,0]

cm = confusion_matrix(y_true,y_pred)
print("confusion matrics")
print(cm)

confusion matrics
[[4 1]
 [1 4]]


In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error
import numpy as np

real_score = [90,60,80,100]

predicted_score = [85,70,70,95]

mae = mean_absolute_error(real_score,predicted_score)
mse = mean_squared_error(real_score,predicted_score)
rmse = root_mean_squared_error(real_score,predicted_score)

print("MAE: On average off by:",mae)
print("MSE: Squared Mistake value:",mse)
print("RMSE: Final Realistic error:",rmse)



MAE: On average off by: 7.5
MSE: Squared Mistake value: 62.5
RMSE: Final Realistic error: 7.905694150420948


In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error
import numpy as np

data = pd.read_csv("Student.csv")

x = data[["Hours"]]
y = data["Score"]

model = LinearRegression()
model.fit(x,y)

predicted_score = model.predict(x)

mae = mean_absolute_error(y,predicted_score)
mse = mean_squared_error(y,predicted_score)
rmse = np.sqrt(mse)

print("Mean Absolute ERROR (MAE):",mae)
print("Mean Squared ERROR (MSE):",mse)
print("Root Mean Squared ERROR (RMSE):",rmse)

""" new_hour = float(input("Enter a hour ="))
new_pred = model.predict(new_hour)
print(f"prediction for {new_hour} is score ={new_pred}") """
